### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by wangshunping** [eugene-eeo/mailthon#25]
guo@pingdeMacBook-Air-2 grid-mail$ python main.py
Traceback (most recent call last):
  File "main.py", line 31, in <module>
    'cats.gif',
  File "/Library/Python/2.7/site-packages/mailthon/postman.py", line 91, in send
    return self.deliver(conn, envelope)
  File "/Library/Python/2.7/site-packages/mailthon/postman.py", line 81, in deliver
    envelope.string(),
  File "/Library/Python/2.7/site-packages/mailthon/envelope.py", line 81, in string
    return self.mime().as_string()
  File "/Library/Python/2.7/site-packages/mailthon/envelope.py", line 72, in mime
    self.headers.prepare(mime)
  File "/Library/Python/2.7/site-packages/mailthon/headers.py", line 90, in prepare
    self[key].encode("utf-8")
AttributeError: 'NoneType' object has no attribute 'encode'

**Comment by eugene-eeo** [comment]
Hi, without seeing the full code snippet it is impossible to tell which header is missing from the dictionary. Can you show me the full code snippet?

**Comment by wangshunping** [comment]
Thanks for reply.

Actually I was meeting mistake when running your first web script.

I have noticed two messages:
 1. when I use your web example with library smtplib, (of course change some config), it is run correct!
 2. when I using wrong password, it is correct raise authentication failed.

Thanks for your help.

**Comment by wangshunping** [comment]
I have reply your through email and I am not sure if you can see the pic.

here is code 

# -*- coding: utf-8 -*-

from mailthon import postman, email

smtp = postman(host='smtp.163.com', port=25, auth=('18355193212@163.com', 'wrongpassword'))
smtp.send(email(
    sender='Me <18355193212@163.com>',
    receivers=['Them <18355193212@163.com>'],
    content='<html><p>Hi!</p></html>',
    attachments=[
        'cats.gif',
    ]
))


message is like that:

Traceback (most recent call last):
  File "main.py", line 11, in <module>
    'cats.gif',
  File "/Library/Python/2.7/site-packages/mailthon/postman.py", line 91, in send
    return self.deliver(conn, envelope)
  File "/Library/Python/2.7/site-packages/mailthon/postman.py", line 81, in deliver
    envelope.string(),
  File "/Library/Python/2.7/site-packages/mailthon/envelope.py", line 81, in string
    return self.mime().as_string()
  File "/Library/Python/2.7/site-packages/mailthon/envelope.py", line 72, in mime
    self.headers.prepare(mime)
  File "/Library/Python/2.7/site-packages/mailthon/headers.py", line 90, in prepare
    self[key].encode("utf-8")
AttributeError: 'NoneType' object has no attribute 'encode'

**Comment by eugene-eeo** [comment]
Ah, it seems like you are missing a subject field. Ideally it should be required, but currently we aren't able to fix it easily. Seems like it's going to go down into the future 0.2.0 release. To fix:

```python
smtp = postman(host='smtp.163.com', port=25, auth=('18355193212@163.com', 'wrongpassword'))
smtp.send(email(
    sender='Me <18355193212@163.com>',
    subject='something-here',
    receivers=['Them <18355193212@163.com>'],
    content='<html><p>Hi!</p></html>',
    attachments=[
        'cats.gif',
    ]
))
```

**Comment by wangshunping** [comment]
WOW～～～

It works ! thanks a lot, I will give your a star.
